### ISSUE TITLE
Unknown class

### ISSUE THREAD

**Issue by iOS-Blog** [yeahdongcn/RSBarcodes_Swift#10]
2014-11-29 02:48:10.998 *[1259:60b] Unknown class _TtC10RSBarcodes26RSCodeReaderViewController in Interface Builder file.

**Comment by daande** [comment]
I am getting this same error:

2015-09-06 09:32:19.815 [435:42355] Unknown class _TtC10RSBarcodes26RSCodeReaderViewController in Interface Builder file.

1.  I set up the following:

![image](https://cloud.githubusercontent.com/assets/3680231/9704618/a85aae5c-547a-11e5-8bbc-a631386f0cd5.png)

2. I dragged in a view controller and set the custom class:

![image](https://cloud.githubusercontent.com/assets/3680231/9704621/beec0738-547a-11e5-8d61-fa460b04af53.png)

3.  In RSCodeReaderController.swift I added the methods described in the getting started:

![image](https://cloud.githubusercontent.com/assets/3680231/9704631/041fb552-547b-11e5-84ce-4a08ca250037.png)

**Comment by daande** [comment]
Alright I just figured this one out.  You need to update the getting started section.  I could do that if you want.

**Comment by yeahdongcn** [comment]
Please! I may not describe this clear enough.
