### ISSUE TITLE
How can I generate interleaved2of5 barcode?

### ISSUE THREAD

**Issue by damboscolo** [yeahdongcn/RSBarcodes_Swift#119]
I can't generate interleaved2of5 barcode image. This is my code, it's the same as the example, I just changed the `machineReadableCodeObjectType` and it's returning nil.

```
        let gen = RSUnifiedCodeGenerator.shared
        gen.fillColor = UIColor.white
        gen.strokeColor = UIColor.black
        print ("generating image with barcode: " + barcode)
        if let image = gen.generateCode(barcode, machineReadableCodeObjectType: AVMetadataObject.ObjectType.interleaved2of5.rawValue) {
            self.barcodeImageView.layer.borderWidth = 1
            self.barcodeImageView.image = RSAbstractCodeGenerator.resizeImage(image, targetSize: self.barcodeImageView.bounds.size, contentMode: UIViewContentMode.bottomRight)
        }
```

**Comment by damboscolo** [comment]
It's a little urgent! I just want to know.

**Comment by yeahdongcn** [comment]
I just tried your code, it works well generating interleaved2of5 barcode.

Are you sure the barcode is valid and the attributes of self.barcodeImageView are correct?

**Comment by damboscolo** [comment]
Oh, it's working!

Sorry, I was using a fake barcode to generate and it was wrong. It was working with the others except this one, I thought I might have something wrong.

Anyway, thanks for the reply!

**Comment by yeahdongcn** [comment]
Great!
