### ISSUE TITLE
Type 'UIApplication' has no member 'NSNotification'

### ISSUE THREAD

**Issue by JLApp2** [yeahdongcn/RSBarcodes_Swift#125]
Hi there,
I have the following issues: 
Type 'UIApplication' has no member 'NSNotification'.
Any help would greatly appreciated.
Najib

**Comment by yeahdongcn** [comment]
Could you please show me your code?

**Comment by JLApp2** [comment]
<img width="1042" alt="rsb" src="https://user-images.githubusercontent.com/28648996/50893981-6ea04c80-1402-11e9-95b0-cbd252da8085.png">
I have tried in other versions of simulators.

**Comment by JLApp2** [comment]
The issue resolved by updating to Swift 4.2.

**Comment by tibm** [comment]
@JLApp2  This should be using the latest Swift changes:

`UIApplication.willEnterForegroundNotification` and
`UIApplication.didEnterBackgroundNotification`
were renamed to
`NSNotification.Name.UIApplicationWillEnterForeground` and `NSNotification.Name.UIApplicationDidEnterBackground`
