### ISSUE TITLE
What is 'crazy mode'?

### ISSUE THREAD

**Issue by winzig** [yeahdongcn/RSBarcodes_Swift#13]
Re: https://github.com/yeahdongcn/RSBarcodes_Swift/commit/37f3de0d6ee35e832b592050910055331ad4cb34

I saw your recent commit for "crazy mode," but was wondering if you could explain what this mode does? I looked around to see if I could find a mention here of Klenov Dmitry to see if there was already a discussion about it, but did not see any.

**Comment by yeahdongcn** [comment]
Since the continuous autofocus is not that fast enough, now I used an API on iOS 8 to change the lens position in near zone very quickly to achieve the new 'continuous autofocus'.

**Comment by winzig** [comment]
Ahhh, thanks for the explanation, sounds good.
