### ISSUE TITLE
Compiler Errors in Xcode 10.2.1

### ISSUE THREAD

**Issue by getaaron** [yeahdongcn/RSBarcodes_Swift#130]
![image](https://user-images.githubusercontent.com/789577/58362613-9696c680-7e5e-11e9-8719-f6e7c712140c.png)

These still need to be updated

https://github.com/yeahdongcn/RSBarcodes_Swift/blob/354e85113787d0a8ea169b97ea942d8e2e2eb069/Source/RSCodeReaderViewController.swift#L372-L373

https://github.com/yeahdongcn/RSBarcodes_Swift/blob/354e85113787d0a8ea169b97ea942d8e2e2eb069/Source/RSCodeReaderViewController.swift#L383-L384

**Comment by yeahdongcn** [comment]
Are you still using Swift 4?
