### ISSUE TITLE
Cocoapods and/or Carthage?

### ISSUE THREAD

**Issue by daniel-reckoder** [yeahdongcn/RSBarcodes_Swift#14]
Hi. It seems that neither Cocoapods nor Carthage are working right now. Are you planing to include this?

**Comment by yeahdongcn** [comment]
Just pushed to Cocoapods and I am new to Carthage, it may take some time for me to get started.

**Comment by yeahdongcn** [comment]
Carthage is done.

These two ways to install will make the app project only works on iOS 8 and above.

**Comment by daniel-reckoder** [comment]
Thanks!

**Comment by yeahdongcn** [comment]
I also updated the README, you may take a look.

**Comment by daniel-reckoder** [comment]
I only see this change: https://github.com/yeahdongcn/RSBarcodes_Swift/commit/b4970509f428b0f1cf8c5976cdfc110f120b67e9
