### ISSUE TITLE
Barcode handler not displaying barcodes when placed in Container View

### ISSUE THREAD

**Issue by arogozin** [yeahdongcn/RSBarcodes_Swift#18]
I created a container view that was placed in the main view. Main view does not use RSCodeReaderViewController, but the view inside container view does. When I get to run the app, it displays the preview layer and I can alternate stroke colors,  self.focusMarkLayer.strokeColor = UIColor.redColor().CGColor. However, when I point to the barcode, nothing gets displayed. What am I doing wrong?

**Comment by yeahdongcn** [comment]
Could you send me your project?
