### ISSUE TITLE
Find Type

### ISSUE THREAD

**Issue by dinaramalho** [yeahdongcn/RSBarcodes_Swift#21]
I would like to create an application which receives various types of bar codes. How can I detect the type of code you are reading?

Thanks for the help

**Comment by yeahdongcn** [comment]
You can print out `self.output.metadataObjectTypes` in `RSCodeReaderViewController.swift` to see all available types.

**Comment by dinaramalho** [comment]
I had researched and found the solution. But thanks anyway.
