### ISSUE TITLE
beta 7 and swift 2.0

### ISSUE THREAD

**Issue by cj-zeiger** [yeahdongcn/RSBarcodes_Swift#22]
Is there any plans to update this for swift 2.0.

Should be a matter of converting and a bit of clean up. I'm not familiar enough with this library and swift to help myself otherwise I would.

**Comment by yeahdongcn** [comment]
Yeah, I will create a Swift 2.0 branch later, I've already got a updated
version locally

Best Regards,
Ye Xiaodong
*http://R0CKSTAR.zai360.com* <http://R0CKSTAR.zai360.com>

**Comment by yeahdongcn** [comment]
Please check https://github.com/yeahdongcn/RSBarcodes_Swift/tree/Swift-2.0
