### ISSUE TITLE
Performing Action When a Barcode Is Scanned

### ISSUE THREAD

**Issue by drewanton** [yeahdongcn/RSBarcodes_Swift#23]
I am building an app that utilizes QR code scanning. What I am trying to do in my `ScanViewController` is to scan a QR code, validate what was scanned, and then segue with the scanned data. Currently, when a QR code is detected, my UI freezes, and shortly after I get an error and memory dump:

> 'NSInternalInconsistencyException', reason: 'Only run on the main thread!'.

Maybe, this isn't the right place to validate the QR code or isn't the right place to segue, but if not, I'm wondering where the validation and segue should take place. My only other requirement is that the validation only occurs when a QR code is detected, which I believe to happen when captureOutput() is called in RSCodeReaderViewController.

```swift
class ScanViewController: RSCodeReaderViewController{
    // Class Variables
    var finalObject: IBuiltCode?
    let ObjectHelper = ObjectBuilder() // Service to validate and build valid scanned objects

    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.focusMarkLayer.strokeColor = UIColor.redColor().CGColor
        self.cornersLayer.strokeColor = UIColor.yellowColor().CGColor
        
        self.tapHandler = { point in
            println(point)
        }
        
        self.barcodesHandler = { barcodes in
            for barcode in barcodes {
                println("Barcode found: type=" + barcode.type + " value=" + barcode.stringValue)
                // returns nil if invalid (can provide validateAndBuild func code if necessary)
                var builtObject = self.ObjectHelper.validateAndBuild(barcode,
                      scannedData: barcode.stringValue)
                if builtObject != nil{
                    println("Good object.")
                    self.performQR()
                }
            }
        }
    }

    func performQR(){
        performSegueWithIdentifier("toQR", sender: self)
    }
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        if (segue.identifier == "toQR"){
            let QRVC: QRViewController = segue.destinationViewController as! QRViewController
            QRVC.receivedObject = finalObject as? QRObject
        }
    }
}
```

**Comment by yeahdongcn** [comment]
func performQR(){
        dispatch_async(dispatch_get_main_queue(), { () -> Void in
            self.performSegueWithIdentifier("toQR", sender: self)
        })
    }
You need to switch to main thread to perform UI related operations.

**Comment by yeahdongcn** [comment]
The barcodesHandler was designed non thread safe, because we may perform some actions which may take long time.

**Comment by yeahdongcn** [comment]
Could you try the code I provided?

**Comment by drewanton** [comment]
Thank you very much for the reply. I am unable to test the code tonight, but I will tomorrow.

**Comment by drewanton** [comment]
I tested the code and it does perform the segue. My only issue now is that the segue is performed multiple times and doesn't just stop after a valid scan happened. Is there a way to stop the scanning process immediately after a valid scan took place?

 ```swift
    self.barcodesHandler = { barcodes in
        for barcode in barcodes {
            println("Barcode found: type=" + barcode.type + " value=" + barcode.stringValue)
            
            if let builtObject = self.ObjectHelper.validateAndBuild(barcode,
                scannedData: barcode.stringValue){ // If built object is valid
                    self.performQR()
            }
        }
    }
 ```

**Comment by yeahdongcn** [comment]
You can add a `break` after you call `self.performQR()`

**Comment by drewanton** [comment]
Unfortunately, adding the break still causes multiple segues to occur. A solution I found is to add `self.session.stopRunning()` before `self.performQR()` and then add a `break`. Is it safe to stop the session like this?

```swift
self.barcodesHandler = { barcodes in
    for barcode in barcodes {
        println("Barcode found: type=" + barcode.type + " value=" + barcode.stringValue)
        if let builtObject = self.ObjectHelper.validateAndBuild(barcode,
            scannedData: barcode.stringValue){ // If built object is valid
                self.finalObject = builtObject // Assign finalObject for segue purposes
                self.session.stopRunning()
                break
        }
        else {
            self.displayInvalidScan()
        }
    }
    self.handleSegue()
}
```

**Comment by yeahdongcn** [comment]
Yeah, you're right, I forgot this line.

**Comment by drewanton** [comment]
I posted this [conversation](http://stackoverflow.com/q/31521973/4975117) to SO to be more reachable.

**Comment by yeahdongcn** [comment]
Great, thank you!

**Comment by Gerst20051** [comment]
:+1:
