### ISSUE TITLE
Swift 2.0 Branch - Build Fails on new branch.

### ISSUE THREAD

**Issue by cj-zeiger** [yeahdongcn/RSBarcodes_Swift#24]
<img width="860" alt="screen shot 2015-07-16 at 11 42 11 am" src="https://cloud.githubusercontent.com/assets/5673861/8727808/b99e6eae-2baf-11e5-9e2a-d17f55c4b374.png">
Steps to reproduce:
1. Clone repo to local
`git clone git@github.com:yeahdongcn/RSBarcodes_Swift.git`
2. Checkout Swift-2.0 branch. 
`git checkout origin/Swift-2.0`
2. Open RSBarcodes_Swift project in xcode beta 7
3. Set deployment target to iOS 8.0 or 9.0, happens for both.
4. Attempt to build library

As seen below, there are a few more errors as well when trying to build this new branch.
<img width="261" alt="screen shot 2015-07-16 at 11 44 01 am" src="https://cloud.githubusercontent.com/assets/5673861/8727852/f83c9b9a-2baf-11e5-9eea-bf9ea226e123.png">

**Comment by yeahdongcn** [comment]
Could you tell me your Xcode version, I built the project using Xcode 7 beta 3
<img width="530" alt="default" src="https://cloud.githubusercontent.com/assets/2831050/8737088/42720df2-2c51-11e5-8329-b8069d6da422.png">

**Comment by cj-zeiger** [comment]
I'm still in 7.0. Updating now to see if that resolves the issues.

**Comment by cj-zeiger** [comment]
Updating to 7.3 fixed this issue.
