### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by johnliedtke** [yeahdongcn/RSBarcodes_Swift#26]
I'm getting a build error with the swift2 branch when installing using carthage:

.../RSBarcodes_Swift/Source/RSCodeGenerator.swift:159:76: error: value of optional type 'CIImage?' not unwrapped; did you mean to use '!' or '?'?
.../RSBarcodes_Swift/Source/RSCodeGenerator.swift:159:53: error: value of optional type 'CIImage?' not unwrapped; did you mean to use '!' or '?'?

**Comment by yeahdongcn** [comment]
Which version of Xcode-beta are you using?

**Comment by yeahdongcn** [comment]
I have committed a new change to Swift 2.0 branch, please pull it.
