### ISSUE TITLE
Cannot Compile on Xcode 7 Beta 6 (7A192o)

### ISSUE THREAD

**Issue by julianrichie** [yeahdongcn/RSBarcodes_Swift#28]
advance has been explicitly marked unavailable here (Swift.advance)
![screen shot 2015-08-28 at 8 13 47 pm](https://cloud.githubusercontent.com/assets/1916616/9547012/5e4bbcee-4dc1-11e5-9a3c-59aebd1786fa.png)

**Comment by yeahdongcn** [comment]
It will be fixed this weekend.

**Comment by yeahdongcn** [comment]
Please see the Swift-2.0 branch.
