### ISSUE TITLE
Swift-2.0 branch podspec?

### ISSUE THREAD

**Issue by Morse-Code** [yeahdongcn/RSBarcodes_Swift#30]
I would like to use Swift-2.0 branch but it seems the 2.0 podspec is the same as master so these is no way to use the 2.0 code via cocopods. Is this correct or am I missing something?

I'd like to do something like: 

```ruby
pod 'RSBarcodes_Swift', :git => 'https://github.com/yeahdongcn/RSBarcodes_Swift.git', :branch => 'Swift-2.0'```

[Update] Seems as though entering the above actually did work for my Swift 2.0 project. Not quite sure why it didn't use the latest tag from master.

**Comment by yeahdongcn** [comment]
I tried in my side and I got the same error, but I don't know how to fix...
Since the Xcode7 get released recently, please use `pod 'RSBarcodes_Swift', '~> 0.1.0'` to install.
