### ISSUE TITLE
Xcode does not recognize the class when creating a new file

### ISSUE THREAD

**Issue by cloud-tribal** [yeahdongcn/RSBarcodes_Swift#34]
Hi

Installed using Cocoapods, went through the reader process and when I get to the point where I need to choose a subclass for ScanViewController, RSCodeReaderViewController isn't there. 

However, if I hard code RSCodeReaderViewController as a subclass, and cmd+click on RSCodeReaderViewController in the file, I successfully get directed to its implementation.

Nonetheless the ScanViewController file throws multiple errors, the first one indicating "Use of undeclared type 'RSCodeReaderViewController'". 

Any ideas?

**Comment by AngeloGiurano** [comment]
Why did you close it? How did you solve this?

**Comment by daande** [comment]
Generally in XCode after selecting a subclass within the Storyboard you have to press the Enter key on your keyboard I have read others saying the same thing. @cloud-tribal was the readme I wrote for the cocoapods installation successful?

**Comment by AngeloGiurano** [comment]
@daande Im having the same problem actually, I cant find the RSCodeReaderViewController and if I try to subclass it programmaticaly I get this
<img width="894" alt="screenshot 2015-10-28 13 50 41" src="https://cloud.githubusercontent.com/assets/6850571/10788952/04e835ee-7d7b-11e5-9319-849c4b2e54d5.png">

**Comment by AngeloGiurano** [comment]
Im using XCode 7.1

**Comment by daande** [comment]
@AngeloGiurano Can you paste your podfile?

**Comment by AngeloGiurano** [comment]
@daande PodFile:

```target 'TestApp' do
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode7’
    pod 'RSBarcodes_Swift', :git => 'https://github.com/yeahdongcn/RSBarcodes_Swift.git', :branch => 'Swift2.0’
end

target 'TestAppTests' do
    
end

use_frameworks!```

and from terminal:

<img width="561" alt="screenshot 2015-10-28 14 14 00" src="https://cloud.githubusercontent.com/assets/6850571/10789514/2642e0c4-7d7e-11e5-884a-630fd2876c3f.png">

**Comment by daande** [comment]
1. Ensure you are now opening the workspace file not the project one.
2. Can you do a clean / build
3. Ensure you have import RSBarcodes_Swift in the class file also

**Comment by AngeloGiurano** [comment]
It worked after importing the class, strange because I've tried that earlier, the clean/build must have done the thing! Thanks a lot!

**Comment by daande** [comment]
@AngeloGiurano no problem I am glad I could help.
