### ISSUE TITLE
Active Scanning Area

### ISSUE THREAD

**Issue by Gerst20051** [yeahdongcn/RSBarcodes_Swift#43]
I can't seem to figure out why the barcodes are only scanned when it's in the top half of the camera feed. This is true in portrait and landscape orientation. Is this expected behavior?

**Comment by yeahdongcn** [comment]
The frame of the camera feed takes the bounds of the root view of RSCodeReaderViewController, maybe you should add a print in RSCodeReaderViewController's viewDidLoad()

if let videoPreviewLayer = self.videoPreviewLayer {
            videoPreviewLayer.videoGravity = AVLayerVideoGravityResizeAspectFill
            print(self.view.bounds)
            videoPreviewLayer.frame = self.view.bounds
            self.view.layer.addSublayer(videoPreviewLayer)
        }

**Comment by Gerst20051** [comment]
Hey, I forgot I created this issue but I figured it out. It only scans when it's directly in the center of the screen. I can be anywhere horizontally along the vertical center (equator) of the screen. If you extend the red line all the way to the edges of the screen.

![img_7673](https://cloud.githubusercontent.com/assets/235372/13538300/c588874e-e217-11e5-8da2-5e14c9d4025e.jpg)

**Comment by dbpfindexp** [comment]
@Gerst20051 how did you get the scanning area guides to display?  I would like to add something similar to help users understand the scan area.

**Comment by Gerst20051** [comment]
The scan area is the horizontal red line. you can create them yourself.
