### ISSUE TITLE
Where are the "delightful controls?"

### ISSUE THREAD

**Issue by Alamoz** [yeahdongcn/RSBarcodes_Swift#45]
The title of your project mentions "delightful controls," yet they apparently are nowhere to be found and undocumented. Are there any controls for a RSCodeReaderViewController, and if so how do they work?

Thank you!

**Comment by yeahdongcn** [comment]
There are 3 layers you can use to display generated code image (RSCodeLayer), captured code (RSCornersLayer), camera focus (RSFocusMarkLayer).
