### ISSUE TITLE
InputCorrectionLevel is incorrect

### ISSUE THREAD

**Issue by bdrelling** [yeahdongcn/RSBarcodes_Swift#48]
I hope only the comments are wrong!

    public enum InputCorrectionLevel: String {
        case Medium = "M"   // 7%
        case Low = "L"      // 15% default
        case Quarter = "Q"  // 25%
        case High = "H"     // 30%
    }

**Comment by yeahdongcn** [comment]
That's my fault, I've merged a PR without examine it carefully. I will fix this today.
