### ISSUE TITLE
Code39Generator Uppercase Limitation

### ISSUE THREAD

**Issue by bdrelling** [yeahdongcn/RSBarcodes_Swift#49]
The following block in RSCode39Generator.swift checks the contents against the .uppercaseString:

```
override public func isValid(contents: String) -> Bool {
        let length = contents.length()
        if length > 0 && contents == contents.uppercaseString {
            for character in contents.characters {
                let location = CODE39_ALPHABET_STRING.location(String(character))
                if location == NSNotFound {
                    return false
                }
            }
            return true
        }
        return false
    }
```

Other libraries (like `zxing` and `barcodelib`) will simply uppercase the contents and check to make sure afterwards.

Should we do this within RSBarcodes as well?

**Comment by yeahdongcn** [comment]
According to the code 39 spec, it only accepts the uppercase characters,
digits and a few symbols. This validation is to ensure the user input is
correct and I think the generator should not change the contents.

Best Regards,
Ye Xiaodong
*http://R0CKSTAR.zai360.com* <http://R0CKSTAR.zai360.com>
