### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by codywinton** [yeahdongcn/RSBarcodes_Swift#54]
Can you add Release notes for new releases?

**Comment by yeahdongcn** [comment]
OK, you mean a change log file?

**Comment by codywinton** [comment]
Yeah, that could work. Otherwise, you can add notes like so: https://github.com/Alamofire/Alamofire/releases

**Comment by yeahdongcn** [comment]
I have to say I tried 😁

https://github.com/yeahdongcn/RSBarcodes_Swift/releases/tag/0.1.9
