### ISSUE TITLE
Please add PDF417

### ISSUE THREAD

**Issue by ufoloko** [yeahdongcn/RSBarcodes_Swift#58]
Please add PDF417 support for your component.

Thanks

**Comment by huntermonk** [comment]
You can actually just pass `"org.iso.PDF417"` (what `AVMetadataObjectTypePDF417Code` resolves to).

**Comment by yeahdongcn** [comment]
You can generate PDF417 image by calling
        let pdf417r = g.generateCode("123456", machineReadableCodeObjectType: AVMetadataObjectTypePDF417Code)
        XCTAssert(pdf417r != nil, "Pass PDF417")

**Comment by huntermonk** [comment]
Unfortunately none of the `AVMetadataObjectType` strings are being exposed for me. I'm guessing this is the problem that @ufoloko is having.

I've had to go into the code and see what `AVMetadataObjectTypePDF417Code` resolves to make this work.

Would you like me to open up a separate issue @yeahdongcn?

**Comment by yeahdongcn** [comment]
Have you tried to 

    import AVFoundation

These `AVMetadataObjectType` strings are declared in AVFoundation -> AVMetadataObject

**Comment by huntermonk** [comment]
Ah that's embarrassing, I didn't know that. Thanks for the great fix.

I'm most likely going to submit a PR with some suggested changes to the `README.md`. Thanks for the wonderful library!

**Comment by yeahdongcn** [comment]
That will be grateful, thank you in advance!
