### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by treyrich** [yeahdongcn/RSBarcodes_Swift#61]
Need to add Swift 3 support to library.

**Comment by Gerst20051** [comment]
👍

**Comment by Gerst20051** [comment]
👍 here is my pull request i made before seeing this. will close it once we get swift 3 support implemented. https://github.com/yeahdongcn/RSBarcodes_Swift/pull/64/files

**Comment by zeusent** [comment]
What's the status on this? I see a Swift 3.0 branch but I just tried it now and it doesn't compile with the latest Xcode 8 beta version.

**Comment by bdrelling** [comment]
Checking status again too....

**Comment by zeusent** [comment]
Swift 3 support is here. Jut use the Swift-3.0 branch in your Podfile for now until it gets pushed into master.

**Comment by zeusent** [comment]
@yeahdongcn is the Swift-3.0 branch going to be merges at some point? I'd love to remove my Podfile workaround for this pod :)

**Comment by yeahdongcn** [comment]
It will be done tomorrow

**Comment by yeahdongcn** [comment]
Done, please use 

    pod 'RSBarcodes_Swift', '~> 3.0'

for Swift 3.0

    pod 'RSBarcodes_Swift', '~> 2.3'

for Swift 2.3
