### ISSUE TITLE
Downcast issue

### ISSUE THREAD

**Issue by julianrichie** [yeahdongcn/RSBarcodes_Swift#68]
hi, i'm getting this Downcasting error for the Swift 3.0 branch
<img width="717" alt="screen shot 2016-08-29 at 12 40 24 pm" src="https://cloud.githubusercontent.com/assets/1916616/18041734/1c947e76-6de6-11e6-88c8-2f74f0a9abca.png">
<img width="407" alt="screen shot 2016-08-29 at 12 40 49 pm" src="https://cloud.githubusercontent.com/assets/1916616/18041736/1d4d7552-6de6-11e6-8e92-407460d88978.png">

**Comment by yeahdongcn** [comment]
Please add one line here

        // MARK: NOTE: If you want to detect specific barcode types, you should update the types
        let types = NSMutableArray(array: self.output.availableMetadataObjectTypes)
        // MARK: NOTE: Uncomment the following line remove QRCode scanning capability
        // types.removeObject(AVMetadataObjectTypeQRCode)
        types.removeObject(AVMetadataObjectTypeFace) // Add 
        self.output.metadataObjectTypes = NSArray(array: types) as [AnyObject]

**Comment by julianrichie** [comment]
ok thanks, i'll try it
