### ISSUE TITLE
Code 39 include "*" symbol

### ISSUE THREAD

**Issue by Darktt** [yeahdongcn/RSBarcodes_Swift#73]
I create a barcode image use code 39,
But content string contents "_" symbol,
Then image generated, "_" is invalid symbol in code 39,
Can exclude this symbol.

**Comment by yeahdongcn** [comment]
Could you provide me your content string?

**Comment by Darktt** [comment]
That string is "*-+%$./"/

**Comment by yeahdongcn** [comment]
Yes, you're right, I updated the validation for content string, string with "*" will be considered as not valid.
