### ISSUE TITLE
RSBarcodes.framework

### ISSUE THREAD

**Issue by marquiano** [yeahdongcn/RSBarcodes_Swift#74]
Hi guys, sorry to bother you about this but I wasn't able to run the project, it seems there are the RSBarcodes.framework file missing.
Can you help me, please?

**Comment by yeahdongcn** [comment]
Could you provide your steps to run the project? And Xcode version?

**Comment by marquiano** [comment]
The the steps I went to:
1 - I create a new project and saved it on desktop
2 - I went in terminal and create the pod file (pod init)
3 - Edit the pod file and update it with the code:
       use_frameworks! 
       pod 'RSBarcodes_Swift' (I took the ", '~> 3.0' "because it was not working)
4 - Saved the pod file
5 - Pod install
I'm currently using xcode 7.3
MacBook-Pro:RSBarcodes_Swift marquiano$ pod --version
1.0.1

Did I something wrong? I tried to use carthage but it didn't work as well (it was my first time I used carthage)
Thanks in advance.

**Comment by yeahdongcn** [comment]
Please change the Podfile content to 

    use_frameworks! 
    pod 'RSBarcodes_Swift', '~> 0.1.9'

If you're using Xcode 7.3, or upgrade your Xcode to the latest 8.0.

**Comment by marquiano** [comment]
Hi,

Thanks for your answer. It downloaded without any warning but I'm worried
about it because when I run the project it didn't do nothing, it seems
there is some classes missing like RSCodeReaderViewController.swift
and BarcodeDisplayViewController.swift.
Is this classes created automatically or it should be create when I
downloaded the project?

Regards.

Marquiano Okopny
SCM - Support Center Manager
ISO 20000 Foundations
Cobit 4.1 Foundations
ITIL Foundations
IBM Cloud Computing Architecture V2 Foundations

"O céu é o limite - The sky is the limit - Le ciel est la limite - Der
Himmel ist die Begrenzung - Ο ουρανός είναι το όριο - Il cielo è il limite
- Небо будет пределом - El cielo es el límite"

2016-09-29 3:42 GMT-03:00 R0CKSTAR <notifications@github.com>:

**Comment by yeahdongcn** [comment]
Hello,

I know your problem now, you just integrated the lib to your own project, if you want to use it, please follow Usage part in the readme. If you want to try it, you can download/clone the repo, open the RSBarcodesSample.xcodeproj under RSBarcodes_Swift/RSBarcodesSample/ folder and run it.
