### ISSUE TITLE
[CIContext initWithOptions:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by CjStone10** [yeahdongcn/RSBarcodes_Swift#75]
[CIContext initWithOptions:]: unrecognized selector sent to instance
This crash can be reproduced in iOS 8.

**Comment by CjStone10** [comment]
I found a solution for this problem. I tried and seems that it's fine.
http://stackoverflow.com/questions/39939415/cicontext-initwithoptions-unrecognized-selector-sent-to-instance

**Comment by CjStone10** [comment]
Nobody wants to solve this issue? :)

**Comment by yeahdongcn** [comment]
I will download the iOS 8 simulator today and try to reproduce this.

**Comment by yeahdongcn** [comment]
I reproduced this issue, that's weird.

**Comment by yeahdongcn** [comment]
[https://github.com/yeahdongcn/RSBarcodes_Swift/commit/a2a2b0e3a1cdce76a3628db9fddd639cec2fc7d1](url)

**Comment by yeahdongcn** [comment]
Fixed, please  see https://github.com/yeahdongcn/RSBarcodes_Swift/releases/tag/3.0.3

**Comment by CjStone10** [comment]
Can you solve this issue also for swift 2.3? Seems that is solved only for swift 3.0.

**Comment by yeahdongcn** [comment]
Done 2.3.1

**Comment by CjStone10** [comment]
Thanks

**Comment by yeahdongcn** [comment]
2.3.1 is build break, please use 2.3.3
