### ISSUE TITLE
createCGImage fails on iOS 8

### ISSUE THREAD

**Issue by codytwinton** [yeahdongcn/RSBarcodes_Swift#77]
`RSCodeGenerator.swift line:185` calls this function:

`createCGImage(outputImage, from: outputImage.extent)`

However, the variable `extent` is only available in iOS 9 and up. So, the code fails on iOS 8.

**Comment by yeahdongcn** [comment]
/* Return a rect the defines the bounds of non-(0,0,0,0) pixels */
    open var extent: CGRect { get }

I have not seen any @available declaration here, anything I was missing?

**Comment by codytwinton** [comment]
@yeahdongcn I guess you're correct. I thought I saw an `@available iOS 9 +`, but I must have been wrong.
