### ISSUE TITLE
Barcode content type

### ISSUE THREAD

**Issue by viral-etymon** [yeahdongcn/RSBarcodes_Swift#79]
Hi,

Is there any way that I can easily identify which of content this barcode contain.

For e.g.
1) QR Code > with VCard
2) QR Code > with URL
3) QR Code > with SMS

OR I need to do it my self from stringValue?

Thanks

**Comment by yeahdongcn** [comment]
Probably you have to write the logic by yourself. This lib only provides code => string conversion, you can use the regular expression to check the format of the string. I think there are a lot of code snippets to do the validations.
