### ISSUE TITLE
Class ContextMaker is implemented in both in RSBarcodes and RSBarcodes_Swift.  One of the two will be used. Which one is undefined 

### ISSUE THREAD

**Issue by oskar9** [yeahdongcn/RSBarcodes_Swift#96]
objc[338]: Class ContextMaker is implemented in both   RSBarcodes.framework/RSBarcodes  and    Frameworks/RSBarcodes_Swift.framework/RSBarcodes_Swift.     One of the two will be used. Which one is undefined.

**Comment by yeahdongcn** [comment]
Please integrate RSBarcodes_Swift or RSBarcodes, not both.
